@startuml messege
participant RABITMQ_SERVER AS R

box "Consolidador" #LightBlue
participant LISTENER AS L
participant CANCEL_OPERATION AS O
participant RABITMQ_SERVICES AS RS
participant CONSOLIDOR_GW AS CG
participant CONSOLIDOR_CORE AS CC
end box
R->L: NUEVO MSG
L->O: SEND NOTIF
O->RS: GET MSG
RS<->R: GET MSG
RS->O: SEND MSG
O->O: PROCESA MSG
O->CG: CANCEL TICKET
CG->CC: CAMBIA ESTADO RESERVA
GW->O: RESERVA CANCELADA
O->O: PROCESE RESPUESTA
O->RS: ENVIE MENSAGE
RS->R: SEND MSG